// <auto-generated />
namespace FashionBangla.Migrations.Security
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201704150328553_UserDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
